In [ ]:
# Numpy
# List (Python)<Arrays(Numpy)
# Since these arrays are 50x mor effecient

In [1]:
import numpy as np

In [4]:
# Creating an array
a=np.array([1,2,3,4,5])

In [5]:
print(a)

[1 2 3 4 5]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


##### Nd array means n-dimensional array(can have 1d, 2d or nd dimensions)

In [7]:
b=np.array([6,7,8,9],dtype=float)

In [9]:
print(type(b[0]))
print(type(a[0]))

<class 'numpy.float64'>
<class 'numpy.int32'>


Integer-> int 32  
Float->  float 64  

In [10]:
# 2dimenstional array
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
print(len(c))

2


In [12]:
print(len(c[0]))

5


In [13]:
print(type(c[0]))

<class 'numpy.ndarray'>


Just like c++ waala 

<!-- These are the data types jo hain -->

In [15]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
1
2


In [27]:
d=np.array([[[1,2,3,4,5],[6,7,8,9,10],[23,45,13,13,12]],[[11,12,13,14,15],[16,17,18,19,20],[23,23,23,23,23]]])

In [28]:
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [23, 45, 13, 13, 12]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [23, 23, 23, 23, 23]]])

In [29]:
d.ndim


3

In [30]:
d.shape

(2, 3, 5)

In [31]:
print(d[0].shape)

(3, 5)


2 for there are 2 elements  
3 for in every element there are 3 elements 
in every 3 there are 5  

Example-> 

In [32]:
print(d.shape)
print(d[0].shape)
print(d[0][0].shape)

(2, 3, 5)
(3, 5)
(5,)


In [35]:
# d[0,2] to access a specific element
# d[0:2] 0 index se lekar 2 index tak ke elements( a range)

In [36]:
# zeros and ones method in array

In [40]:
g=np.zeros(2)

In [41]:
g

array([0., 0.])

In [42]:
# if 2d or more
g=np.zeros((2,3))

In [43]:
g

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
g=np.zeros((2,3,4))

In [46]:
g

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Remember one array-> divide into multiple like here above zeros waala to no of element same hone chaiye

##### Make a mtrix of values in which all the values are same

In [49]:
i=np.full((3,8),99)

In [50]:
i

array([[99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99]])

In [51]:
np.random.rand(4,4)
# Generation of random numbers in the range of 0 to 1

array([[0.69249871, 0.50061985, 0.13688731, 0.2529119 ],
       [0.31399224, 0.99718741, 0.29751738, 0.32033404],
       [0.40602833, 0.79798409, 0.13052647, 0.62893902],
       [0.77760108, 0.61610596, 0.29976565, 0.12449501]])

In [52]:
np.random.randint(1,100,size=(4,5))

array([[65, 29, 48, 53, 11],
       [23, 77, 51, 88, 38],
       [20, 47, 18,  5, 62],
       [41, 14, 57, 27, 96]])

#### Image Processing

In [53]:
# every image can be structured in an array format, with its pixels defining the associated shape and colours