In [1]:
import cv2
import numpy as np
image = cv2.imread('line_art.png', cv2.IMREAD_GRAYSCALE)
_, binary_image = cv2.threshold(image, 128, 255, cv2.THRESH_BINARY)

ModuleNotFoundError: No module named 'cv2'

In [3]:
import svgpathtools
file=r"C:/Users/pooja/Downloads/curvetop/problems/frag0.svg"
# Load the SVG file
svg_file = file
paths, attributes = svgpathtools.svg2paths(svg_file)


In [5]:
bezier_curves = []

for path in paths:
    for segment in path:
        if isinstance(segment, svgpathtools.path.Line):
            # Convert line segments to cubic Bezier curves
            start = segment.start
            end = segment.end
            # Approximate straight lines with Bezier curves
            control1 = start + (end - start) / 3
            control2 = start + 2 * (end - start) / 3
            bezier_curves.append((start, control1, control2, end))
        elif isinstance(segment, svgpathtools.path.CubicBezier):
            # Directly use cubic Bezier segments
            bezier_curves.append((segment.start, segment.control1, segment.control2, segment.end))
        # Handle other segment types similarly


In [6]:
for path in paths:
    for segment in path:
        if isinstance(segment, svgpathtools.path.QuadraticBezier):
            # Convert quadratic Bezier to cubic Bezier
            start = segment.start
            control = segment.control
            end = segment.end
            control1 = start + 2 / 3 * (control - start)
            control2 = end + 2 / 3 * (control - end)
            bezier_curves.append((start, control1, control2, end))


In [7]:
import svgwrite

# Create a new SVG drawing
dwg = svgwrite.Drawing('output.svg', profile='tiny')

# Add Bezier curves to the drawing
for curve in bezier_curves:
    start, control1, control2, end = curve
    path_data = f'M {start.real},{start.imag} C {control1.real},{control1.imag} {control2.real},{control2.imag} {end.real},{end.imag}'
    dwg.add(dwg.path(d=path_data, fill='none', stroke='black'))

# Save the SVG file
dwg.save()


In [15]:
# other
import cv2
image = cv2.imread(r'frag1.png', cv2.IMREAD_GRAYSCALE)

# Apply thresholding
_, binary_image = cv2.threshold(image, 128, 255, cv2.THRESH_BINARY)

In [16]:
# edge detection
edges = cv2.Canny(binary_image, 100, 200)


In [17]:
print(edges)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:

from skimage.morphology import skeletonize
from skimage import img_as_ubyte

skeleton = skeletonize(binary_image // 255)
skeleton = img_as_ubyte(skeleton)


In [22]:
from bezier import DCRBezierFitter

# Extract points from the skeleton
points = np.column_stack(np.nonzero(skeleton))

# Fit cubic Bezier curves to the points
bezier_curves = DCRBezierFitter.fit(points, error=1.0)  # Custom parameters for fitting


ModuleNotFoundError: No module named 'bezier'